### ISSUE TITLE
Ionic 4 Cordova Android app crashes when loading ad

### ISSUE THREAD

**Issue by alexp25** [notmedia/cordova-plugin-adcolony#5]
I wanted to use this plugin in my Ionic 4 Cordova app to escape the AdMob monopoly but encountered the following crash when trying to load an ad. I have followed the same steps as in https://github.com/ferdil/AdColonyCordovaDemo

```
08-23 13:25:49.252  2068  2319 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.sendPluginResult(org.apache.cordova.PluginResult)' on a null object reference
08-23 13:25:49.252  2068  2319 E AndroidRuntime: 	at com.adcolony.plugin.AdColonyPlugin$1.onRequestNotFilled(AdColonyPlugin.java:106)
08-23 13:25:49.252  2068  2319 E AndroidRuntime: 	at com.adcolony.sdk.AdColony.requestInterstitial(SourceFile:780)
08-23 13:25:49.252  2068  2319 E AndroidRuntime: 	at com.adcolony.plugin.AdColonyPlugin$11.run(AdColonyPlugin.java:346)
08-23 13:25:49.252  2068  2319 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-23 13:25:49.252  2068  2319 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-23 13:25:49.252  2068  2319 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
```

**Comment by Yasshs** [comment]
hello are u find the solution ?
